### ISSUE TITLE
Crash when dragging robot around

### ISSUE THREAD

**Issue by 69-69-69** [MelbourneHighSchoolRobotics/ev3sim#44]
The simulator crashed when dragging the robot around. It seems to have something to do with pick_up_interactor.py and the velocity calculation. It might also have something to do with a bug in the pymunk dependancy.

Command prompt log is below:

C:\Users\andrew>ev3sim bot.yaml bot.yaml
Loading chipmunk for Windows (64bit) [C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pymunk\chipmunk.dll]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
An error occured in the Simulation thread. Raising an error now...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\ev3sim.exe\__main__.py", line 7, in <module>
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ev3sim\sim.py", line 59, in main
    raise r[1]
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ev3sim\sim.py", line 39, in run
    runFromConfig(config, shared_data)
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ev3sim\simulation\loader.py", line 153, in runFromConfig
    sl.simulate()
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ev3sim\simulation\loader.py", line 125, in simulate
    interactor.handleEvent(event)
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ev3sim\presets\pick_up_interactor.py", line 66, in handleEvent
    self.obj.body.velocity = self.VELOCITY_MULT * differences
  File "C:\Users\andrew\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pymunk\body.py", line 233, in _set_velocity
    cp.cpBodySetVelocity(self._body, tuple(vel))
TypeError: 'int' object is not iterable

**Comment by glipR** [comment]
Thanks for the issue. I'm aware of this bug, it occurs when you click a robot rather than drag. I can make a fix but will keep this issue open until its merged.
